// Input translation for the current Wayland seat.
//
// The xkbcommon lifecycle follows the Wayland reference backend retained in
// seed/. Its MIT notice is retained in seed/LICENSE.txt.

#include "WaylandInput.h"

#include <cstddef>
#include <stdexcept>
#include <utility>

#include <linux/input-event-codes.h>
#include <wayland-client-protocol.h>
#include <xkbcommon/xkbcommon-keysyms.h>
#include <xkbcommon/xkbcommon-names.h>
#include <xkbcommon/xkbcommon.h>

namespace Scalpel {

namespace {

Scintilla::Keys KeyFromKeysym(xkb_keysym_t keysym) noexcept {
	switch (keysym) {
	case XKB_KEY_Down:
	case XKB_KEY_KP_Down:
		return Scintilla::Keys::Down;
	case XKB_KEY_Up:
	case XKB_KEY_KP_Up:
		return Scintilla::Keys::Up;
	case XKB_KEY_Left:
	case XKB_KEY_KP_Left:
		return Scintilla::Keys::Left;
	case XKB_KEY_Right:
	case XKB_KEY_KP_Right:
		return Scintilla::Keys::Right;
	case XKB_KEY_Home:
	case XKB_KEY_KP_Home:
		return Scintilla::Keys::Home;
	case XKB_KEY_End:
	case XKB_KEY_KP_End:
		return Scintilla::Keys::End;
	case XKB_KEY_Page_Up:
	case XKB_KEY_KP_Page_Up:
		return Scintilla::Keys::Prior;
	case XKB_KEY_Page_Down:
	case XKB_KEY_KP_Page_Down:
		return Scintilla::Keys::Next;
	case XKB_KEY_Delete:
	case XKB_KEY_KP_Delete:
		return Scintilla::Keys::Delete;
	case XKB_KEY_Insert:
	case XKB_KEY_KP_Insert:
		return Scintilla::Keys::Insert;
	case XKB_KEY_Escape:
		return Scintilla::Keys::Escape;
	case XKB_KEY_BackSpace:
		return Scintilla::Keys::Back;
	case XKB_KEY_Tab:
	case XKB_KEY_KP_Tab:
	case XKB_KEY_ISO_Left_Tab:
		return Scintilla::Keys::Tab;
	case XKB_KEY_Return:
	case XKB_KEY_KP_Enter:
		return Scintilla::Keys::Return;
	case XKB_KEY_KP_Add:
		return Scintilla::Keys::Add;
	case XKB_KEY_KP_Subtract:
		return Scintilla::Keys::Subtract;
	case XKB_KEY_KP_Divide:
		return Scintilla::Keys::Divide;
	default:
		break;
	}

	// Scintilla's command map uses upper-case identifiers independently of
	// the text generated by the active xkb state.
	if (keysym >= XKB_KEY_a && keysym <= XKB_KEY_z) {
		keysym += XKB_KEY_A - XKB_KEY_a;
	}
	if (keysym >= 0x20 && keysym <= 0x7e) {
		return static_cast<Scintilla::Keys>(keysym);
	}
	return static_cast<Scintilla::Keys>(0);
}

bool ModifierActive(xkb_state *state, const char *name) noexcept {
	return xkb_state_mod_name_is_active(state, name, XKB_STATE_MODS_EFFECTIVE) > 0;
}

int PointerButton(uint32_t button) noexcept {
	switch (button) {
	case BTN_LEFT:
		return 0;
	case BTN_RIGHT:
		return 1;
	case BTN_MIDDLE:
		return 2;
	default:
		return -1;
	}
}

}

WaylandInput::WaylandInput() : context(xkb_context_new(XKB_CONTEXT_NO_FLAGS)) {
	if (!context) {
		throw std::runtime_error("could not create the xkbcommon context");
	}
}

WaylandInput::~WaylandInput() noexcept {
	if (state) {
		xkb_state_unref(state);
	}
	if (keymap) {
		xkb_keymap_unref(keymap);
	}
	xkb_context_unref(context);
}

bool WaylandInput::SetKeymap(std::string_view keymapText) {
	if (keymapText.empty()) {
		return false;
	}
	xkb_keymap *newKeymap = xkb_keymap_new_from_buffer(context, keymapText.data(),
		keymapText.size(), XKB_KEYMAP_FORMAT_TEXT_V1, XKB_KEYMAP_COMPILE_NO_FLAGS);
	if (!newKeymap) {
		return false;
	}
	xkb_state *newState = xkb_state_new(newKeymap);
	if (!newState) {
		xkb_keymap_unref(newKeymap);
		return false;
	}
	if (state) {
		xkb_state_unref(state);
	}
	if (keymap) {
		xkb_keymap_unref(keymap);
	}
	keymap = newKeymap;
	state = newState;
	return true;
}

void WaylandInput::ResetKeyboardState() {
	if (!keymap) {
		return;
	}
	xkb_state *newState = xkb_state_new(keymap);
	if (!newState) {
		return;
	}
	if (state) {
		xkb_state_unref(state);
	}
	state = newState;
}

void WaylandInput::UpdateModifiers(uint32_t depressed, uint32_t latched,
	uint32_t locked, uint32_t group) {
	if (state) {
		xkb_state_update_mask(state, depressed, latched, locked, 0, 0, group);
	}
}

void WaylandInput::RecordKey(uint32_t time, uint32_t key, bool pressed) {
	if (!state) {
		return;
	}
	const xkb_keycode_t keycode = key + 8;
	KeyboardInput input;
	input.key = KeyFromKeysym(xkb_state_key_get_one_sym(state, keycode));
	input.modifiers = CurrentModifiers();
	input.time = time;
	input.pressed = pressed;
	if (pressed) {
		const int length = xkb_state_key_get_utf8(state, keycode, nullptr, 0);
		if (length > 0) {
			input.text.resize(static_cast<size_t>(length) + 1);
			xkb_state_key_get_utf8(state, keycode, input.text.data(), input.text.size());
			input.text.resize(static_cast<size_t>(length));
		}
	}
	inputs.emplace_back(std::move(input));
}

void WaylandInput::RecordPointerMotion(uint32_t time, double x, double y) {
	pointerX = x;
	pointerY = y;
	inputs.emplace_back(PointerInput{
		PointerAction::Move, CurrentModifiers(), x, y, 0, 0, time, -1});
}

void WaylandInput::RecordPointerLeave() {
	inputs.emplace_back(PointerInput{
		PointerAction::Leave, CurrentModifiers(), pointerX, pointerY});
}

void WaylandInput::RecordPointerButton(uint32_t time, uint32_t button, bool pressed) {
	const int translatedButton = PointerButton(button);
	if (translatedButton < 0) {
		return;
	}
	inputs.emplace_back(PointerInput{
		pressed ? PointerAction::Press : PointerAction::Release,
		CurrentModifiers(), pointerX, pointerY, 0, 0, time, translatedButton});
}

void WaylandInput::RecordPointerAxis(uint32_t time, uint32_t axis, double value) {
	if (axis != WL_POINTER_AXIS_HORIZONTAL_SCROLL && axis != WL_POINTER_AXIS_VERTICAL_SCROLL) {
		return;
	}
	inputs.emplace_back(PointerInput{
		PointerAction::Scroll, CurrentModifiers(), pointerX, pointerY,
		axis == WL_POINTER_AXIS_HORIZONTAL_SCROLL ? value : 0,
		axis == WL_POINTER_AXIS_VERTICAL_SCROLL ? value : 0, time, -1});
}

std::vector<InputEvent> WaylandInput::TakeInputs() {
	return std::exchange(inputs, {});
}

Scintilla::KeyMod WaylandInput::CurrentModifiers() const {
	if (!state) {
		return Scintilla::KeyMod::Norm;
	}
	return Scintilla::ModifierFlags(
		ModifierActive(state, XKB_MOD_NAME_SHIFT),
		ModifierActive(state, XKB_MOD_NAME_CTRL),
		ModifierActive(state, XKB_MOD_NAME_ALT),
		false,
		ModifierActive(state, XKB_MOD_NAME_LOGO));
}

}
