// Input translation for the current Wayland seat.
//
// The xkbcommon lifecycle follows the Wayland reference backend retained in
// seed/. Its MIT notice is retained in seed/LICENSE.txt.

#include "WaylandInput.h"

#include <algorithm>
#include <cstddef>
#include <cstdlib>
#include <stdexcept>
#include <string>
#include <utility>

#include <linux/input-event-codes.h>
#include <wayland-client-protocol.h>
#include <xkbcommon/xkbcommon-compose.h>
#include <xkbcommon/xkbcommon-keysyms.h>
#include <xkbcommon/xkbcommon-names.h>
#include <xkbcommon/xkbcommon.h>

namespace Scalpel {

namespace {

constexpr double PointerAxisStep = 10.0;

std::string_view ComposeLocale() noexcept {
	for (const char *name : {"LC_ALL", "LC_CTYPE", "LANG"}) {
		if (const char *value = std::getenv(name); value && *value) {
			return value;
		}
	}
	return "C";
}

Scintilla::Keys KeyFromKeysym(xkb_keysym_t keysym) noexcept {
	switch (keysym) {
	case XKB_KEY_Down:
	case XKB_KEY_KP_Down:
		return Scintilla::Keys::Down;
	case XKB_KEY_Up:
	case XKB_KEY_KP_Up:
		return Scintilla::Keys::Up;
	case XKB_KEY_Left:
	case XKB_KEY_KP_Left:
		return Scintilla::Keys::Left;
	case XKB_KEY_Right:
	case XKB_KEY_KP_Right:
		return Scintilla::Keys::Right;
	case XKB_KEY_Home:
	case XKB_KEY_KP_Home:
		return Scintilla::Keys::Home;
	case XKB_KEY_End:
	case XKB_KEY_KP_End:
		return Scintilla::Keys::End;
	case XKB_KEY_Page_Up:
	case XKB_KEY_KP_Page_Up:
		return Scintilla::Keys::Prior;
	case XKB_KEY_Page_Down:
	case XKB_KEY_KP_Page_Down:
		return Scintilla::Keys::Next;
	case XKB_KEY_Delete:
	case XKB_KEY_KP_Delete:
		return Scintilla::Keys::Delete;
	case XKB_KEY_Insert:
	case XKB_KEY_KP_Insert:
		return Scintilla::Keys::Insert;
	case XKB_KEY_Escape:
		return Scintilla::Keys::Escape;
	case XKB_KEY_BackSpace:
		return Scintilla::Keys::Back;
	case XKB_KEY_Tab:
	case XKB_KEY_KP_Tab:
	case XKB_KEY_ISO_Left_Tab:
		return Scintilla::Keys::Tab;
	case XKB_KEY_Return:
	case XKB_KEY_KP_Enter:
		return Scintilla::Keys::Return;
	case XKB_KEY_KP_Add:
		return Scintilla::Keys::Add;
	case XKB_KEY_KP_Subtract:
		return Scintilla::Keys::Subtract;
	case XKB_KEY_KP_Divide:
		return Scintilla::Keys::Divide;
	default:
		break;
	}

	// Scintilla's command map uses upper-case identifiers independently of
	// the text generated by the active xkb state.
	if (keysym >= XKB_KEY_a && keysym <= XKB_KEY_z) {
		keysym += XKB_KEY_A - XKB_KEY_a;
	}
	if (keysym >= 0x20 && keysym <= 0x7e) {
		return static_cast<Scintilla::Keys>(keysym);
	}
	return static_cast<Scintilla::Keys>(0);
}

bool ModifierActive(xkb_state *state, const char *name) noexcept {
	return xkb_state_mod_name_is_active(state, name, XKB_STATE_MODS_EFFECTIVE) > 0;
}

int PointerButton(uint32_t button) noexcept {
	switch (button) {
	case BTN_LEFT:
		return 0;
	case BTN_RIGHT:
		return 1;
	case BTN_MIDDLE:
		return 2;
	default:
		return -1;
	}
}

}

WaylandInput::WaylandInput() : WaylandInput(ComposeLocale()) {
}

WaylandInput::WaylandInput(std::string_view composeLocale) :
	context(xkb_context_new(XKB_CONTEXT_NO_FLAGS)) {
	if (!context) {
		throw std::runtime_error("could not create the xkbcommon context");
	}
	const std::string locale(composeLocale);
	composeTable = xkb_compose_table_new_from_locale(
		context, locale.c_str(), XKB_COMPOSE_COMPILE_NO_FLAGS);
	if (composeTable) {
		composeState = xkb_compose_state_new(composeTable, XKB_COMPOSE_STATE_NO_FLAGS);
		if (!composeState) {
			xkb_compose_table_unref(composeTable);
			composeTable = nullptr;
		}
	}
}

WaylandInput::~WaylandInput() noexcept {
	if (state) {
		xkb_state_unref(state);
	}
	if (keymap) {
		xkb_keymap_unref(keymap);
	}
	if (composeState) {
		xkb_compose_state_unref(composeState);
	}
	if (composeTable) {
		xkb_compose_table_unref(composeTable);
	}
	xkb_context_unref(context);
}

bool WaylandInput::SetKeymap(std::string_view keymapText) {
	if (keymapText.empty() || keymapText.back() != '\0') {
		return false;
	}
	xkb_keymap *newKeymap = xkb_keymap_new_from_buffer(context, keymapText.data(),
		keymapText.size() - 1, XKB_KEYMAP_FORMAT_TEXT_V1, XKB_KEYMAP_COMPILE_NO_FLAGS);
	if (!newKeymap) {
		return false;
	}
	xkb_state *newState = xkb_state_new(newKeymap);
	if (!newState) {
		xkb_keymap_unref(newKeymap);
		return false;
	}
	if (state) {
		xkb_state_unref(state);
	}
	if (keymap) {
		xkb_keymap_unref(keymap);
	}
	keymap = newKeymap;
	state = newState;
	ResetCompose();
	return true;
}

void WaylandInput::ResetKeyboardState() {
	ResetCompose();
	if (!keymap) {
		return;
	}
	xkb_state *newState = xkb_state_new(keymap);
	if (!newState) {
		return;
	}
	if (state) {
		xkb_state_unref(state);
	}
	state = newState;
}

void WaylandInput::ResetKeyboardDevice() {
	ResetCompose();
	const bool reportFocusLoss = keyboardFocused || std::any_of(
		inputs.begin(), inputs.end(), [](const InputEvent &input) {
			const auto *focus = std::get_if<KeyboardFocusInput>(&input);
			return focus && !focus->focused;
		});
	inputs.erase(std::remove_if(inputs.begin(), inputs.end(), [](const InputEvent &input) {
		return std::holds_alternative<KeyboardFocusInput>(input) ||
			std::holds_alternative<KeyboardInput>(input);
	}), inputs.end());
	keyboardFocused = false;
	if (reportFocusLoss) {
		inputs.emplace_back(KeyboardFocusInput{false});
	}
	if (state) {
		xkb_state_unref(state);
		state = nullptr;
	}
	if (keymap) {
		xkb_keymap_unref(keymap);
		keymap = nullptr;
	}
}

void WaylandInput::ResetPointerDevice() {
	const bool reportLeave = pointerFocused || std::any_of(
		inputs.begin(), inputs.end(), [](const InputEvent &input) {
			const auto *pointer = std::get_if<PointerInput>(&input);
			return pointer && pointer->action == PointerAction::Leave;
		});
	inputs.erase(std::remove_if(inputs.begin(), inputs.end(), [](const InputEvent &input) {
		return std::holds_alternative<PointerInput>(input);
	}), inputs.end());
	for (size_t button = 0; button < pointerButtons.size(); button++) {
		if (pointerButtons[button]) {
			inputs.emplace_back(PointerInput{PointerAction::Release, CurrentModifiers(),
				pointerX, pointerY, 0, 0, 0, static_cast<int>(button)});
			pointerButtons[button] = false;
		}
	}
	if (reportLeave) {
		pointerFocused = true;
		RecordPointerLeave();
	} else {
		pointerX = 0;
		pointerY = 0;
	}
	pointerFrames = false;
	ResetPointerFrame();
}

void WaylandInput::SetPointerVersion(uint32_t version) noexcept {
	pointerFrames = version >= WL_POINTER_FRAME_SINCE_VERSION;
	ResetPointerFrame();
}

void WaylandInput::RecordKeyboardFocus(bool focused) {
	if (!focused) {
		ResetCompose();
	}
	if (focused != keyboardFocused) {
		keyboardFocused = focused;
		inputs.emplace_back(KeyboardFocusInput{focused});
	}
}

void WaylandInput::UpdateModifiers(uint32_t depressed, uint32_t latched,
	uint32_t locked, uint32_t group) {
	if (state) {
		xkb_state_update_mask(state, depressed, latched, locked, 0, 0, group);
	}
}

void WaylandInput::RecordKey(uint32_t time, uint32_t key, bool pressed) {
	if (!state) {
		return;
	}
	const xkb_keycode_t keycode = key + 8;
	KeyboardInput input;
	const xkb_keysym_t keysym = xkb_state_key_get_one_sym(state, keycode);
	input.key = KeyFromKeysym(keysym);
	input.modifiers = CurrentModifiers();
	input.time = time;
	input.pressed = pressed;
	if (pressed) {
		input.text = TextForKey(keycode, keysym, input.modifiers);
	}
	inputs.emplace_back(std::move(input));
}

std::string WaylandInput::TextForKey(
	uint32_t keycode, uint32_t keysym, Scintilla::KeyMod modifiers) {
	const Scintilla::KeyMod commandModifiers = Scintilla::KeyMod::Ctrl |
		Scintilla::KeyMod::Alt | Scintilla::KeyMod::Super | Scintilla::KeyMod::Meta;
	if ((modifiers & commandModifiers) != Scintilla::KeyMod::Norm) {
		return {};
	}

	if (composeState &&
		xkb_compose_state_feed(composeState, keysym) == XKB_COMPOSE_FEED_ACCEPTED) {
		switch (xkb_compose_state_get_status(composeState)) {
		case XKB_COMPOSE_COMPOSING:
			return {};
		case XKB_COMPOSE_COMPOSED: {
			const int length = xkb_compose_state_get_utf8(composeState, nullptr, 0);
			std::string text;
			if (length > 0) {
				text.resize(static_cast<size_t>(length) + 1);
				xkb_compose_state_get_utf8(composeState, text.data(), text.size());
				text.resize(static_cast<size_t>(length));
			}
			ResetCompose();
			return text;
		}
		case XKB_COMPOSE_CANCELLED:
			ResetCompose();
			return {};
		case XKB_COMPOSE_NOTHING:
			break;
		}
	}

	const int length = xkb_state_key_get_utf8(state, keycode, nullptr, 0);
	std::string text;
	if (length > 0) {
		text.resize(static_cast<size_t>(length) + 1);
		xkb_state_key_get_utf8(state, keycode, text.data(), text.size());
		text.resize(static_cast<size_t>(length));
	}
	return text;
}

void WaylandInput::ResetCompose() noexcept {
	if (composeState) {
		xkb_compose_state_reset(composeState);
	}
}

void WaylandInput::RecordPointerMotion(uint32_t time, double x, double y) {
	pointerFocused = true;
	pointerX = x;
	pointerY = y;
	inputs.emplace_back(PointerInput{
		PointerAction::Move, CurrentModifiers(), x, y, 0, 0, time, -1});
}

void WaylandInput::RecordPointerLeave() {
	if (!pointerFocused) {
		return;
	}
	pointerFocused = false;
	inputs.emplace_back(PointerInput{
		PointerAction::Leave, CurrentModifiers(), pointerX, pointerY});
}

void WaylandInput::RecordPointerButton(uint32_t time, uint32_t button, bool pressed) {
	const int translatedButton = PointerButton(button);
	if (translatedButton < 0) {
		return;
	}
	pointerButtons[static_cast<size_t>(translatedButton)] = pressed;
	inputs.emplace_back(PointerInput{
		pressed ? PointerAction::Press : PointerAction::Release,
		CurrentModifiers(), pointerX, pointerY, 0, 0, time, translatedButton});
}

void WaylandInput::RecordPointerAxis(uint32_t time, uint32_t axis, double value) {
	const std::optional<size_t> index = PointerAxisIndex(axis);
	if (!index) {
		return;
	}
	if (pointerFrames) {
		PointerAxisState &state = pointerAxes[*index];
		state.continuous += value;
		state.hasContinuous = true;
		pointerAxisTime = time;
		return;
	}
	inputs.emplace_back(PointerInput{
		PointerAction::Scroll, CurrentModifiers(), pointerX, pointerY,
		axis == WL_POINTER_AXIS_HORIZONTAL_SCROLL ? value : 0,
		axis == WL_POINTER_AXIS_VERTICAL_SCROLL ? value : 0, time, -1});
}

void WaylandInput::RecordPointerFrame() {
	if (!pointerFrames) {
		return;
	}
	std::array<double, 2> deltas{};
	for (size_t axis = 0; axis < pointerAxes.size(); axis++) {
		const PointerAxisState &state = pointerAxes[axis];
		// Wheel metadata describes the same motion as the continuous axis
		// value, so choose the most current form instead of adding them.
		if (state.hasValue120) {
			deltas[axis] = static_cast<double>(state.value120) * PointerAxisStep / 120.0;
		} else if (state.hasDiscrete) {
			deltas[axis] = static_cast<double>(state.discrete) * PointerAxisStep;
		} else if (state.hasContinuous) {
			deltas[axis] = state.continuous;
		}
	}
	if (deltas[0] != 0 || deltas[1] != 0) {
		inputs.emplace_back(PointerInput{
			PointerAction::Scroll, CurrentModifiers(), pointerX, pointerY,
			deltas[1], deltas[0], pointerAxisTime, -1});
	}
	ResetPointerFrame();
}

void WaylandInput::RecordPointerAxisSource(uint32_t) noexcept {
	// Axis source does not alter the emitted scroll delta.
}

void WaylandInput::RecordPointerAxisStop(uint32_t time, uint32_t axis) noexcept {
	if (pointerFrames) {
		if (const std::optional<size_t> index = PointerAxisIndex(axis)) {
			pointerAxisTime = time;
		}
	}
}

void WaylandInput::RecordPointerAxisDiscrete(uint32_t axis, int32_t discrete) noexcept {
	if (pointerFrames && discrete != 0) {
		if (const std::optional<size_t> index = PointerAxisIndex(axis)) {
			pointerAxes[*index].discrete += discrete;
			pointerAxes[*index].hasDiscrete = true;
		}
	}
}

void WaylandInput::RecordPointerAxisValue120(uint32_t axis, int32_t value120) noexcept {
	if (pointerFrames && value120 != 0) {
		if (const std::optional<size_t> index = PointerAxisIndex(axis)) {
			pointerAxes[*index].value120 += value120;
			pointerAxes[*index].hasValue120 = true;
		}
	}
}

void WaylandInput::RecordPointerAxisRelativeDirection(
	uint32_t, uint32_t) noexcept {
	// Relative direction does not alter the emitted scroll delta.
}

std::vector<InputEvent> WaylandInput::TakeInputs() {
	return std::exchange(inputs, {});
}

Scintilla::KeyMod WaylandInput::CurrentModifiers() const {
	if (!state) {
		return Scintilla::KeyMod::Norm;
	}
	return Scintilla::ModifierFlags(
		ModifierActive(state, XKB_MOD_NAME_SHIFT),
		ModifierActive(state, XKB_MOD_NAME_CTRL),
		ModifierActive(state, XKB_MOD_NAME_ALT),
		false,
		ModifierActive(state, XKB_MOD_NAME_LOGO));
}

std::optional<size_t> WaylandInput::PointerAxisIndex(uint32_t axis) noexcept {
	switch (axis) {
	case WL_POINTER_AXIS_VERTICAL_SCROLL:
		return 0;
	case WL_POINTER_AXIS_HORIZONTAL_SCROLL:
		return 1;
	default:
		return std::nullopt;
	}
}

void WaylandInput::ResetPointerFrame() noexcept {
	pointerAxes = {};
	pointerAxisTime = 0;
}

}
