#!/bin/sh
# Phase 5 completion check: fail while forbidden message-layer forms remain.
# See tools/phase5-boundary.md for the freeze classification and allowlist.
#
# Usage: tools/check-no-message-layer.sh
# Exit 0 only when no unexpected hits remain.

set -eu

script_dir=$(dirname -- "$0")
root=$(CDPATH= cd -- "$script_dir/.." && pwd)
cd "$root"

fail=0

# Paths that are history, allowlist files, or out of build scope for residual counts.
path_excluded() {
	path=$1
	case $path in
	./seed/*|seed/*|./benchmark-results/*|benchmark-results/*|./build/*|build/*|./build-asan/*|build-asan/*|./build-ubsan/*|build-ubsan/*|./.git/*|.git/*)
		return 0 ;;
	./tools/phase5-boundary.md|tools/phase5-boundary.md|./tools/check-no-message-layer.sh|tools/check-no-message-layer.sh)
		return 0 ;;
	./MESSAGE_REMOVAL.md|MESSAGE_REMOVAL.md|./ROADMAP.md|ROADMAP.md|./AGENTS.md|AGENTS.md|./DISCOVERABILITY.md|DISCOVERABILITY.md|./DISCOVERABILITY_LESSONS.md|DISCOVERABILITY_LESSONS.md)
		return 0 ;;
	./tools/discoverability/*|tools/discoverability/*)
		return 0 ;;
	esac
	for pat in $extra_skip; do
		case $path in
		"$pat"|./"$pat") return 0 ;;
		esac
	done
	return 1
}

extra_skip=

check() {
	label=$1
	pattern=$2
	shift 2
	extra_skip=$*

	tmp=${TMPDIR:-/tmp}/phase5-msg-check.$$
	rg -n -e "$pattern" \
		--glob '!seed/**' \
		--glob '!benchmark-results/**' \
		--glob '!build*/**' \
		--glob '!.git/**' \
		. >"$tmp" 2>/dev/null || true

	count=0
	shown=0
	while IFS= read -r line || [ -n "$line" ]; do
		[ -z "$line" ] && continue
		path=${line%%:*}
		if path_excluded "$path"; then
			continue
		fi
		count=$((count + 1))
		if [ "$shown" -lt 40 ]; then
			if [ "$shown" -eq 0 ]; then
				printf 'FAIL %s:\n' "$label"
			fi
			printf '%s\n' "$line"
			shown=$((shown + 1))
		fi
	done <"$tmp"
	rm -f "$tmp"

	if [ "$count" -gt 0 ]; then
		if [ "$count" -gt 40 ]; then
			printf '... (%s more, %s total)\n' $((count - 40)) "$count"
		else
			printf '(%s total)\n' "$count"
		fi
		fail=1
	else
		printf 'ok   %s\n' "$label"
	fi
}

check 'WndProc or DefWndProc' 'WndProc|DefWndProc'

check 'ScintillaMessages.h include or path' 'ScintillaMessages\.h' \
	'scintilla/include/ScintillaMessages.h' \
	'scintilla/include/ScintillaCall.h' \
	'scintilla/include/ScintillaStructures.h'

check 'Message:: cases or casts' 'Message::' \
	'scintilla/include/ScintillaMessages.h'

check 'enum class Message' 'enum class Message' \
	'scintilla/include/ScintillaMessages.h' \
	'scintilla/include/ScintillaStructures.h'

check 'SCI_ or SCN_ constants (non-Lexilla)' 'SCI_[A-Z0-9_]+|SCN_[A-Z0-9_]+' \
	'scintilla/include/Scintilla.h' \
	'scintilla/include/Scintilla.iface' \
	'scintilla/include/Sci_Position.h' \
	'scintilla/include/ILexer.h' \
	'scintilla/include/ILoader.h' \
	'scintilla/ScintillaDoc.html'

check 'Autogenerated section markers' '\+\+Autogenerated|--Autogenerated'

check 'WndProc coercion helpers' 'PtrFromSPtr|ConstCharPtrFromSPtr|CharPtrFromSPtr|UCharPtrFromSPtr|ConstUCharPtrFromSPtr|ViewFromParams|PtrFromUPtr|ConstCharPtrFromUPtr|PositionFromUPtr|LineFromUPtr|SPtrFromUPtr|PointFromParameters|KeysFromWParam|KeyModFromWParam|StringResult|BytesResult|CommandFromMessage'

# Affirmative "call through SCI_/WndProc" instructions in live docs (not historical freeze text).
tmp=${TMPDIR:-/tmp}/phase5-msg-docs.$$
rg -n -e 'send the SCI_|SendMessage|call WndProc|through the message (number|layer|interface)' \
	DISCOVERABILITY.md scintilla/ScintillaDoc.html >"$tmp" 2>/dev/null || true
count=0
shown=0
while IFS= read -r line || [ -n "$line" ]; do
	[ -z "$line" ] && continue
	count=$((count + 1))
	if [ "$shown" -lt 40 ]; then
		if [ "$shown" -eq 0 ]; then
			printf 'FAIL live docs directing through messages:\n'
		fi
		printf '%s\n' "$line"
		shown=$((shown + 1))
	fi
done <"$tmp"
rm -f "$tmp"
if [ "$count" -gt 0 ]; then
	printf '(%s total)\n' "$count"
	fail=1
else
	printf 'ok   live docs directing through messages\n'
fi

if [ "$fail" -ne 0 ]; then
	printf '\ncheck-no-message-layer: residual message-layer forms remain (expected until phase 5 completes).\n' >&2
	printf 'See tools/phase5-boundary.md.\n' >&2
	exit 1
fi

printf '\ncheck-no-message-layer: clean.\n'
exit 0
